name: stream_board
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - alabaster=0.7.12=py37_0
  - anaconda-client=1.11.0=py37haa95532_0
  - anaconda-navigator=2.4.0=py37haa95532_0
  - anyio=3.5.0=py37haa95532_0
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py37h2bbff1b_0
  - arrow=1.2.3=py37haa95532_1
  - astroid=2.6.6=py37haa95532_0
  - atomicwrites=1.4.0=py_0
  - attrs=22.1.0=py37haa95532_0
  - autopep8=1.6.0=pyhd3eb1b0_0
  - babel=2.11.0=py37haa95532_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - bcrypt=3.2.0=py37h2bbff1b_1
  - beautifulsoup4=4.11.1=py37haa95532_0
  - binaryornot=0.4.4=pyhd3eb1b0_1
  - black=22.6.0=py37haa95532_0
  - blas=1.0=mkl
  - bleach=4.1.0=pyhd3eb1b0_0
  - bottleneck=1.3.5=py37h080aedc_0
  - brotlipy=0.7.0=py37h2bbff1b_1003
  - ca-certificates=2024.8.30=h56e8100_0
  - certifi=2024.8.30=pyhd8ed1ab_0
  - cffi=1.15.1=py37h2bbff1b_3
  - chardet=4.0.0=py37haa95532_1003
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.0.4=py37haa95532_0
  - cloudpickle=2.0.0=pyhd3eb1b0_0
  - clr_loader=0.2.6=pyhd8ed1ab_0
  - clyent=1.2.2=py37_1
  - colorama=0.4.6=py37haa95532_0
  - conda=23.1.0=py37haa95532_0
  - conda-content-trust=0.1.1=pyhd3eb1b0_0
  - conda-package-handling=2.0.2=py37haa95532_0
  - conda-package-streaming=0.7.0=py37haa95532_0
  - conda-repo-cli=1.0.4=pyhd3eb1b0_0
  - conda-token=0.4.0=pyhd3eb1b0_0
  - cookiecutter=1.7.3=pyhd3eb1b0_0
  - cryptography=39.0.1=py37h21b164f_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - debugpy=1.5.1=py37hd77b12b_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - diff-match-patch=20200713=pyhd3eb1b0_0
  - docutils=0.18.1=py37haa95532_3
  - entrypoints=0.4=py37haa95532_0
  - fftw=3.3.9=h2bbff1b_2
  - flake8=3.9.2=pyhd3eb1b0_0
  - flit-core=3.6.0=pyhd3eb1b0_0
  - freetype=2.12.1=ha860e81_0
  - greenlet=2.0.1=py37hd77b12b_0
  - icc_rt=2022.1.0=h6049295_2
  - icu=58.2=ha925a31_3
  - idna=3.4=py37haa95532_0
  - imagesize=1.4.1=py37haa95532_0
  - importlib-metadata=4.11.3=py37haa95532_0
  - importlib_metadata=4.11.3=hd3eb1b0_0
  - importlib_resources=5.2.0=pyhd3eb1b0_1
  - inflection=0.5.1=py37haa95532_0
  - intel-openmp=2021.4.0=haa95532_3556
  - intervaltree=3.1.0=pyhd3eb1b0_0
  - ipykernel=6.15.2=py37haa95532_0
  - ipython=7.31.1=py37haa95532_1
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - ipywidgets=7.6.5=pyhd3eb1b0_2
  - isort=5.9.3=pyhd3eb1b0_0
  - jedi=0.18.1=py37haa95532_1
  - jinja2=3.1.2=py37haa95532_0
  - jinja2-time=0.2.0=pyhd3eb1b0_3
  - joblib=1.1.1=py37haa95532_0
  - jpeg=9e=h2bbff1b_1
  - json5=0.9.6=pyhd3eb1b0_0
  - jsonschema=4.17.3=py37haa95532_0
  - jupyter=1.0.0=py37haa95532_8
  - jupyter_client=6.1.12=pyhd3eb1b0_0
  - jupyter_console=6.4.0=pyhd3eb1b0_0
  - jupyter_core=4.11.2=py37haa95532_0
  - jupyter_server=1.23.4=py37haa95532_0
  - jupyterlab=3.5.3=py37haa95532_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_server=2.19.0=py37haa95532_0
  - jupyterlab_widgets=1.0.0=pyhd3eb1b0_1
  - keyring=23.4.0=py37haa95532_0
  - lazy-object-proxy=1.6.0=py37h2bbff1b_0
  - libpng=1.6.39=h8cc25b3_0
  - libsodium=1.0.18=h62dcd97_0
  - libspatialindex=1.9.3=h6c2663c_0
  - libtiff=4.0.8=vc14h04e2a1e_10
  - libwebp=1.2.2=h2bbff1b_0
  - markupsafe=2.1.1=py37h2bbff1b_0
  - matplotlib-inline=0.1.6=py37haa95532_0
  - mccabe=0.6.1=py37haa95532_2
  - menuinst=1.4.19=py37h59b6b97_0
  - mistune=0.8.4=py37hfa6e2cd_1001
  - mkl=2021.4.0=haa95532_640
  - mkl-service=2.4.0=py37h2bbff1b_0
  - mkl_fft=1.3.1=py37h277e83a_0
  - mkl_random=1.2.2=py37hf11a4ad_0
  - mypy_extensions=0.4.3=py37haa95532_1
  - navigator-updater=0.3.0=py37haa95532_0
  - nbclassic=0.5.2=py37haa95532_0
  - nbclient=0.5.13=py37haa95532_0
  - nbconvert=6.4.4=py37haa95532_0
  - nbformat=5.7.0=py37haa95532_0
  - nest-asyncio=1.5.6=py37haa95532_0
  - notebook=6.5.2=py37haa95532_0
  - notebook-shim=0.2.2=py37haa95532_0
  - numexpr=2.8.4=py37h5b0cc5e_0
  - numpy=1.21.5=py37h7a0a035_3
  - numpy-base=1.21.5=py37hca35cd5_3
  - numpydoc=1.5.0=py37haa95532_0
  - openssl=1.1.1q=h8ffe710_0
  - packaging=22.0=py37haa95532_0
  - pandas=1.3.5=py37h6214cd6_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - paramiko=2.8.1=pyhd3eb1b0_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pathspec=0.10.3=py37haa95532_0
  - patsy=0.5.6=pyhd8ed1ab_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pip=22.3.1=py37haa95532_0
  - pkgutil-resolve-name=1.3.10=py37haa95532_0
  - platformdirs=2.5.2=py37haa95532_0
  - pluggy=1.0.0=py37haa95532_1
  - poyo=0.5.0=pyhd3eb1b0_0
  - prometheus_client=0.14.1=py37haa95532_0
  - prompt-toolkit=3.0.36=py37haa95532_0
  - prompt_toolkit=3.0.36=hd3eb1b0_0
  - psutil=5.9.0=py37h2bbff1b_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pycodestyle=2.7.0=pyhd3eb1b0_0
  - pycosat=0.6.4=py37h2bbff1b_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pydocstyle=6.3.0=py37haa95532_0
  - pyflakes=2.3.1=pyhd3eb1b0_0
  - pygments=2.11.2=pyhd3eb1b0_0
  - pyjwt=2.4.0=py37haa95532_0
  - pylint=2.9.6=py37haa95532_1
  - pyls-spyder=0.4.0=pyhd3eb1b0_0
  - pynacl=1.5.0=py37h8cc25b3_0
  - pyopenssl=23.0.0=py37haa95532_0
  - pyparsing=3.0.9=py37haa95532_0
  - pyqt=5.9.2=py37hd77b12b_6
  - pyqtgraph=0.11.0=py_0
  - pyrsistent=0.18.0=py37h196d8e1_0
  - pysocks=1.7.1=py37_1
  - python=3.7.11=h6244533_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-fastjsonschema=2.16.2=py37haa95532_0
  - python-lsp-black=1.0.0=pyhd3eb1b0_0
  - python-lsp-jsonrpc=1.0.0=pyhd3eb1b0_0
  - python-lsp-server=1.2.4=pyhd3eb1b0_0
  - python-slugify=5.0.2=pyhd3eb1b0_0
  - python_abi=3.7=2_cp37m
  - pythonnet=3.0.3=pyhd8ed1ab_0
  - pytoolconfig=1.2.5=py37haa95532_1
  - pytz=2022.7=py37haa95532_0
  - pywin32=305=py37h2bbff1b_0
  - pywin32-ctypes=0.2.0=py37_1001
  - pywinpty=2.0.10=py37h5da7b33_0
  - pyyaml=6.0=py37h2bbff1b_1
  - pyzmq=23.2.0=py37hd77b12b_0
  - qdarkstyle=3.0.2=pyhd3eb1b0_0
  - qstylizer=0.2.2=py37haa95532_0
  - qt=5.9.7=vc14h73c81de_0
  - qtawesome=1.2.2=py37haa95532_0
  - qtconsole=5.4.0=py37haa95532_0
  - qtpy=2.2.0=py37haa95532_0
  - requests=2.28.1=py37haa95532_0
  - rope=1.7.0=py37haa95532_0
  - rtree=1.0.1=py37h2eaa2aa_0
  - ruamel.yaml=0.17.21=py37h2bbff1b_0
  - ruamel.yaml.clib=0.2.6=py37h2bbff1b_1
  - scikit-learn=1.0.2=py37hf11a4ad_1
  - scipy=1.7.3=py37h7a0a035_2
  - seaborn=0.12.2=py37haa95532_0
  - send2trash=1.8.0=pyhd3eb1b0_1
  - setuptools=65.6.3=py37haa95532_0
  - sip=4.19.13=py37hd77b12b_0
  - six=1.16.0=pyhd3eb1b0_1
  - sniffio=1.2.0=py37haa95532_1
  - snowballstemmer=2.2.0=pyhd3eb1b0_0
  - sortedcontainers=2.4.0=pyhd3eb1b0_0
  - soupsieve=2.3.2.post1=py37haa95532_0
  - sphinx=5.0.2=py37haa95532_0
  - sphinxcontrib-applehelp=1.0.2=pyhd3eb1b0_0
  - sphinxcontrib-devhelp=1.0.2=pyhd3eb1b0_0
  - sphinxcontrib-htmlhelp=2.0.0=pyhd3eb1b0_0
  - sphinxcontrib-jsmath=1.0.1=pyhd3eb1b0_0
  - sphinxcontrib-qthelp=1.0.3=pyhd3eb1b0_0
  - sphinxcontrib-serializinghtml=1.1.5=pyhd3eb1b0_0
  - spyder=5.1.5=py37haa95532_1
  - spyder-kernels=2.1.3=py37haa95532_0
  - sqlalchemy=1.4.39=py37h2bbff1b_0
  - sqlite=3.45.3=h2bbff1b_0
  - statsmodels=0.13.5=py37h080aedc_1
  - terminado=0.17.1=py37haa95532_0
  - testpath=0.6.0=py37haa95532_0
  - text-unidecode=1.3=pyhd3eb1b0_0
  - textdistance=4.2.1=pyhd3eb1b0_0
  - threadpoolctl=2.2.0=pyh0d69192_0
  - three-merge=0.1.1=pyhd3eb1b0_0
  - tinycss2=1.2.1=py37haa95532_0
  - tk=8.6.7=vc14hb68737d_1
  - toml=0.10.2=pyhd3eb1b0_0
  - tomli=2.0.1=py37haa95532_0
  - toolz=0.12.0=py37haa95532_0
  - tornado=6.2=py37h2bbff1b_0
  - traitlets=5.7.1=py37haa95532_0
  - typed-ast=1.4.3=py37h2bbff1b_1
  - typing-extensions=4.4.0=py37haa95532_0
  - typing_extensions=4.4.0=py37haa95532_0
  - ujson=5.4.0=py37hd77b12b_0
  - unidecode=1.2.0=pyhd3eb1b0_0
  - urllib3=1.26.14=py37haa95532_0
  - vc=14.2=h2eaa2aa_1
  - vs2015_runtime=14.29.30133=h43f2093_3
  - watchdog=2.1.6=py37haa95532_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py37_1
  - websocket-client=0.58.0=py37haa95532_4
  - wheel=0.38.4=py37haa95532_0
  - widgetsnbextension=3.5.2=py37haa95532_0
  - win_inet_pton=1.1.0=py37haa95532_0
  - wincertstore=0.2=py37haa95532_2
  - winpty=0.4.3=4
  - wrapt=1.12.1=py37he774522_1
  - yaml=0.2.5=he774522_0
  - yapf=0.31.0=pyhd3eb1b0_0
  - zeromq=4.3.4=hd77b12b_0
  - zipp=3.11.0=py37haa95532_0
  - zlib=1.2.13=h8cc25b3_1
  - zstandard=0.19.0=py37h2bbff1b_0
  - pip:
      - brainflow==4.8.2
      - decorator==4.4.2
      - ffmpeg-python==0.2.0
      - fonttools==4.38.0
      - fpdf==1.7.2
      - future==1.0.0
      - imageio==2.31.2
      - imageio-ffmpeg==0.4.9
      - kiwisolver==1.4.5
      - littleutils==0.2.2
      - matplotlib==3.5.3
      - moviepy==1.0.3
      - nptyping==1.4.4
      - opencv-python==4.9.0.80
      - outdated==0.2.2
      - pandas-flavor==0.6.0
      - pillow==9.5.0
      - pingouin==0.5.3
      - plotly==5.18.0
      - proglog==0.1.10
      - pypylon==3.0.1
      - pyqt5==5.15.6
      - pyqt5-qt5==5.15.2
      - pyqt5-sip==12.9.0
      - scikit-posthocs==0.3.4
      - tabulate==0.9.0
      - tenacity==8.2.3
      - tqdm==4.66.1
      - typish==1.9.3
      - xarray==0.20.2
